# Generated by Django 4.1 on 2022-09-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebuka', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='gretings_1',
            new_name='greetings_1',
        ),
        migrations.AlterField(
            model_name='home',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
