# Generated by Django 4.1 on 2022-09-03 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebuka', '0002_rename_gretings_1_home_greetings_1_alter_home_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='catergory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills_set', to='ebuka.category'),
        ),
    ]
